import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Instagram, Facebook, Twitter, Linkedin, Github } from "lucide-react";
import Link from "next/link";

const roboto = Raleway({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Tchami Ernest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${roboto.className} antialiased`}>
        {children}
        <footer className="flex items-center justify-center ">
          <div className="container flex-col  py-5 flex items-center justify-center">
            <div className="text-3xl font-bold cursor-pointer mb-5">
              Tchami Ernest
            </div>
            <p className="text-center text-[12px] px-10">
              I am an experienced Full-stack Developer with a strong focus on
              Node.js and React.js. Throughout my career, I have contributed to
              a diverse range of innovative solutions. I am driven by a passion
              for creating purpose-driven products and solving complex
              challenges through the power of programming. My ultimate goal is
              to develop tools and applications that not only meet technical
              objectives, but also empower users and foster positive change in
              their lives and communities. Additionally, I have implemented
              DevOps best practices, continuous integration/continuous
              deployment (CI/CD), and cloud infrastructure management to enhance
              efficiency and reliability.
            </p>

            <div className="w-full flex gap-3 items-center justify-center mt-5">
              <Link
                href={"https://www.instagram.com/tchamierenest/?hl=en"}
                className="bg-green-500 hover:bg-green-600 h-7 w-7  rounded-full flex items-center justify-center text-black"
              >
                <Instagram className="h-3 w-3" />
              </Link>
              <Link
                href={"/"}
                className="bg-green-500 hover:bg-green-600 h-8 w-8 rounded-full flex items-center justify-center text-black"
              >
                <Facebook className="h-4 w-4" />
              </Link>
              <Link
                href={"https://x.com/Tchamianest4"}
                className="bg-green-500 hover:bg-green-600 h-10 w-10 rounded-full flex items-center justify-center text-black"
              >
                <Github />
              </Link>
              <Link
                href={"https://github.com/ErnestTchami"}
                className="bg-green-500 hover:bg-green-600 h-8 w-8 rounded-full flex items-center justify-center text-black"
              >
                <Twitter className="h-4 w-4" />
              </Link>
              <Link
                href={"https://www.linkedin.com/in/iradukunda-ernest/"}
                className="bg-green-500 hover:bg-green-600 h-7 w-7 rounded-full flex items-center justify-center text-black"
              >
                <Linkedin className="h-3 w-3" />
              </Link>
            </div>
            <div className="w-full bg-zinc-600 h-[1px] mt-5"></div>
            <div className=" text-white py-5 text-center">
              <p>
                Designed by
                <a
                  href="https://github.com/ErnestTchami"
                  className="text-green-500 ml-2 hover:underline"
                >
                  ErnestTchami
                </a>
              </p>
              <p className="mb-0 mt-5">
                Copyright <strong>Ernest Tchami</strong> All Rights Reserved
                &copy; <span id="current-year">{new Date().getFullYear()}</span>
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
